version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/taxi_dispatcher"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxi_dispatcher
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
